export const CATEGORIES = [
  "Electronics",
  "Clothing & Apparel",
  "Home & Kitchen",
  "Books & Literature",
  "Beauty & Personal Care",
  "Sports & Outdoors",
  "Toys & Games",
  "Health & Wellness",
  "Automotive",
  "Jewelry & Watches",
  "Furniture & Decor",
  "Garden & Outdoor Living",
  "Pet Supplies",
  "Office & Stationery",
  "Food & Beverages",
  "Music & Instruments",
  "Arts & Crafts",
  "Baby & Kids",
  "Tools & Home Improvement",
  "Luggage & Travel Gear",
  "Movies & TV Shows",
  "Computers & Accessories",
  "Video Games & Consoles",
  "Cameras & Photography",
  "Shoes & Footwear",
];

export const CATEGORY_COLORS = {
  Electronics: "#3B82F6",
  "Clothing & Apparel": "#EF4444",
  "Home & Kitchen": "#10B981",
  "Books & Literature": "#8B5CF6",
  "Beauty & Personal Care": "#F59E0B",
  "Sports & Outdoors": "#6B7280",
  "Toys & Games": "#EC4899",
  "Health & Wellness": "#0EA5E9",
  Automotive: "#D946EF",
  "Jewelry & Watches": "#84CC16",
  "Furniture & Decor": "#F97316",
  "Garden & Outdoor Living": "#14B8A6",
  "Pet Supplies": "#8B5CF6",
  "Office & Stationery": "#D97706",
  "Food & Beverages": "#059669",
  "Music & Instruments": "#4B5563",
  "Arts & Crafts": "#60A5FA",
  "Baby & Kids": "#FB7185",
  "Tools & Home Improvement": "#34D399",
  "Luggage & Travel Gear": "#A78BFA",
  "Movies & TV Shows": "#FBBF24",
  "Computers & Accessories": "#9CA3AF",
  "Video Games & Consoles": "#F472B6",
  "Cameras & Photography": "#38BDF8",
  "Shoes & Footwear": "#A855F7",
};
