export const CATEGORIES = [
  "Electronics",
  "Clothing & Apparel",
  "Home & Kitchen",
  "Books & Literature",
  "Beauty & Personal Care",
  "Sports & Outdoors",
  "Toys & Games",
  "Health & Wellness",
  "Automotive",
  "Jewelry & Watches",
  "Furniture & Decor",
  "Garden & Outdoor Living",
  "Pet Supplies",
  "Office & Stationery",
  "Food & Beverages",
  "Music & Instruments",
  "Arts & Crafts",
  "Baby & Kids",
  "Tools & Home Improvement",
  "Luggage & Travel Gear",
  "Movies & TV Shows",
  "Computers & Accessories",
  "Video Games & Consoles",
  "Cameras & Photography",
  "Shoes & Footwear",
];
